import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Learn() {
    return (
        <div className={styles.container}>
            <Head>
                <title>The Game</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    <a>Contribute</a>
                </h1>

                <p className={styles.description}>
                    Make this game better
                </p>

                <div>
                    <p className={styles.center}>
                        
                    </p>
              </div>
          </main>

          <footer className={styles.footer}>
              <a
                  href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                  target="_blank"
                  rel="noopener noreferrer"
              >
                  Powered by{' '}
                  <span className={styles.logo}>
                      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                  </span>
              </a>
          </footer>
      </div>
    )
}