import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>The Game</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <Link href="">The Game</Link>
                </h1>

                <p className={styles.description}>
                    The big mulitplayer community game
                </p>

                <div className={styles.grid}>
                    <Link href="/Learn" passHref>
                        <div  className={styles.card}>
                                <a>The Project &rarr;</a>
                                <p>Learn more about The Game!</p>
                        </div>
                    </Link>

                    <Link href="/Play" passHref>
                        <div className={styles.card}>
                            <a>Play Demo &rarr;</a>
                            <p>Coming soon (hopefully)</p>
                        </div>
                    </Link>

                    <Link href="/RoadMap" passHref>
                        <div className={styles.card}>
                            <a>Road map &rarr;</a>
                            <p>See planned features and progress</p>
                        </div>
                    </Link>

                    <Link href="/Contribute" passHref>
                        <div className={styles.card}>
                            <a>Open Source &rarr;</a>
                            <p>Contribute to the project</p>
                        </div>
                    </Link>
              </div>
          </main>

          <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
