import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>The Game</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="">The Game</a>
                </h1>

                <p className={styles.description}>
                    The big mulitplayer community game
                </p>

                <div className={styles.grid}>
                    <a href="/Learn" className={styles.card}>
                        <h2>The Project &rarr;</h2>
                        <p>Learn more about The Game!</p>
                    </a>

                    <a href="/Play" className={styles.card}>
                        <h2>Play Demo &rarr;</h2>
                        <p>Coming soon (hopefully)</p>
                    </a>

                    <a href="/RoadMap" className={styles.card}>
                        <h2>Road map &rarr;</h2>
                        <p>See planned features and progress</p>
                    </a>

                    <a href="/Contribute" className={styles.card}>
                        <h2>Open Source &rarr;</h2>
                        <p>Contribute to the project</p>
                    </a>
              </div>
          </main>

          <footer className={styles.footer}>
              <a
                  href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                  target="_blank"
                  rel="noopener noreferrer"
              >
                  Powered by{' '}
                  <span className={styles.logo}>
                      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                  </span>
              </a>
          </footer>
      </div>
    )
}
